# -*- coding: utf-8 -*-
"""Lab02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S5nFVNHJLmSgPnsIabrcQYuP6OtpV-sI

Problem-1
"""

def product(a,b):
  return a*b;

a = int(input())
b = int(input())

if(product(a,b)>1000):
  print("Sum = ",a+b)
else:
  print("Product = ",product(a,b))

"""Problem-2"""

import math
def pram(r):
  return 2*(math.pi)*r

def area(r):
  return (math.pi)*(r**2)

radius = float(input())

print("Area = ",area(radius))
print("Parameter = ",pram(radius))

"""Problem-3"""

def compound_interest_2019160031(P, R, T):
  return P * (( 1 + ( R/100 ) )**T)

P = float(input())
R = float(input())
T = float(input())

print("A = ",compound_interest_2019160031(P,R,T))

"""Problem-4"""

def series(N):
  sum = 0
  for i in range(1,N+1):
    sum = sum + (i**2)
  return sum

N = int(input())
print("Output = ",series(N))

"""Problem-5"""

def prime_find_2019160031(n):
  if n<2:
    return False
  elif n==2:
    return True
  elif n%2==0:
    return False
  else:
    for i in range(3,N,2):
      if n%i==0:
        return False
  return True

n = int(input())
if prime_find_2019160031(n):
  print("Prime")
else:
  print("Not Prime")

"""Problem-6"""

from re import I
def fib(n):
  if n==1:
    return 0
  elif n==2:
    return 1
  else:
    l=0
    r=1
    sum = l+r
    for i in range(2,n):
      sum = l+r
      l = r
      r = sum
    return sum

n = int(input())
print(n,"th Fibonacci = ",fib(n))

"""Problem-7"""

def sum(a):
  sum = 0
  for i in range(len(a)):
    sum = sum + a[i]
  return sum

list = [1,2,3,4,5]
print("Sum =",sum(list))

"""Problem-8"""

def sum(a):
  sum = 0
  for i in range(len(a)):
    if i%2==0:
      sum = sum + a[i]
  return sum

list = [1,2,3,4,5,6]
print("Sum =",sum(list))

"""**Extra Part: String Method use**"""

str = "HEllO woRLd"
print("String = "+str)
print("String = "+str.capitalize())
print("String = "+str.casefold())
print("String = "+str.center(20))
print("String = ",str.count("woRLd"))
print("String = ",str.encode())
print("String = ",str.endswith("d"))
print("String = ",str.expandtabs())
print("String = ",str.find("E"))
print("String = ",str.format())
print("String = ",str.index("wo"))
print("String = ",str.isalnum())
print("String = ",str.isalpha())
print("String = ",str.isdecimal())
print("String = ",str.isdigit())
print("String = ",str.isidentifier())
print("String = ",str.islower())
print("String = ",str.isnumeric())
print("String = ",str.isprintable())
print("String = ",str.isspace())
print("String = ",str.istitle())
print("String = ",str.isupper())
print("String = ",str.join("J O I N"))
print("String = ",str.lower())
print("String = ",str.ljust(20))
txt = str
temp = txt.maketrans("H","P")
print("String = ",txt.translate(temp))
str = "Hello World Everyone"
print("String = ",str.partition("World"))
print("String = ",str.replace("Hello","Replace"))
print("String = ",str.rfind("World"))
print("String = ",str.rpartition("World"))
print("String = ",str.split())
print("String = ",str.splitlines())
print("String = ",str.startswith('H'))
print("String = ",str.swapcase())
print("String = ",str.title())
print("String = ",str.translate("H"))
print("String = ",str.upper())
str = "100"
print("String = ",str.zfill(20))